### ISSUE TITLE
Project Creation Flow and Team Onboarding

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#1534]
- [ ] brainstorm what we need to accomplish this quarter to improve project creation flow and team onboarding
- [ ] create measurements to know we're improving or not
- [ ] break out work
- [ ] clean up existing issues under this milestone
- [ ] don't forget customer enablement

Known issues we need to fix:
- [ ] when creating a project, you should be able to name the project separately from the primary source
- [ ] ability to edit primary source
- [ ] walk the user through different configurations, explaining how waffle improves their workflow (onboarding!). Statuspage.io has a sweet example, look at other onboarding cases: http://www.useronboard.com/
- [ ] warn the user before creating a project, to avoid cases where events happen without users expecting it
- [ ] team members should have to be allowed to join a private repo, before gaining access (necessary for accounting, since we charge per user)
- [ ] inviting team members
