### ISSUE TITLE
Hover/tooltip on milestone

### ISSUE THREAD

**Issue by mpgerlek** [waffleio/waffle.io#1882]
When hovering over a milestone label, it would be nice to have a tooltip which shows the associated due date (if any).

**Comment by burtonjc** [comment]
As simple as <tag tooltip="{{milestone.due_date}}">

**Comment by homeyer** [comment]
**Acceptance Criteria**
- [ ] make the date human understandable, like "<milestone> due in 3 days", using momentjs
- [ ] use bootstrap default tooltip styling, by using code like `<tag tooltip="tooltip content">`. For an example, see the question mark tooltip on the homepage when logged in.
- [ ] Make sure to include the tooltip name, since it might be truncated
- [ ] works on the card view and the detail view

**Comment by marydavis** [comment]
would you want the description shown as well or just the due date?

**Comment by mpgerlek** [comment]
Just the date is fine - not really enough room for anything more.

-mpg
