### ISSUE TITLE
publicize API

### ISSUE THREAD

**Issue by ashumz** [waffleio/waffle.io#2233]
Our API has had a lot of demand from our users, for the information that Waffle applies on top of GitHub data, like sizing. Additionally, this will enable users to build their own integrations.
- [ ] documentation on readme.io
- [ ] let users register their own Oauth Applications (like GitHub)
- [ ] let users create personal API tokens (like GitHub)

**Comment by justinabrahms** [comment]
Interested in this, given my team has points in waffle and I'd love a way to get them out so we can run our own calculations on it.

**Comment by ryancastle** [comment]
We would be really keen on this too. Particularly, if we had a means of aggregating user points across projects.

**Comment by justinabrahms** [comment]
https://github.com/justinabrahms/waffle-planner

For those who need this, you might consider this script I wrote which temporarily gets around the issue. You just paste it into your developer console.

**Comment by lkodai** [comment]
+1 for getting points to run our own calculations. Especially with user filters.

**Comment by AnaMSteele** [comment]
We are in the process of moving to GraphQL. We are considering making our API public following that move. Closing this issue for the time being, as we are tracking that work separately.
