### ISSUE TITLE
design milestone burndown page

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2349]
**Acceptance Criteria**
- [x] page layout, with:
 - [x] toggle between PRs, Issues & PRs, Issues
 - [x] toggle between count and size
 - [x] select milestone, but keep in consideration selecting labels with dates in the future
 - [x] start/end date selector

**Comment by marydavis** [comment]
![burndown-graph-beta](https://cloud.githubusercontent.com/assets/176437/12693869/1d59fbb6-c6e7-11e5-8aa1-fa4d983c9c56.png)

**Comment by marydavis** [comment]
this is using placeholder button colors, these are not the final button colors

**Comment by homeyer** [comment]
JS error on the main metrics page on staging:
![image](https://dl.dropboxusercontent.com/spa/0nz45d6wl4rw5hj/qxya149t.png)

**Comment by homeyer** [comment]
I don't think I'm seeing what I'm supposed to be seeing :) ![screenshot](https://dl.dropboxusercontent.com/spa/0nz45d6wl4rw5hj/1vakhry6.png)

**Comment by homeyer** [comment]
would be cool to have an example graph with an explanation, sort of envisioning an overlay like this: ![example](https://help.rallydev.com/sites/default/files/multimedia/styles/large/public/reading_bd_chrt_c.jpg) (stolen from [here](https://help.rallydev.com/reading-burndown-chart).

Just a thought, we can create a separate card for something like that if we think it's a good idea. I think what I'm lacking is an explanation of how I should use this, what's good/bad, how I should configure it. Unfortunately most of that isn't UX, it's understanding the purpose of a burndown + knowing how to use it.

**Comment by homeyer** [comment]
I'm a fan of the page design. For the legend, we might want it closer to the graph so it could be included in the one generated by the graph service. What do you think?

And, axis labels would help understand what you're looking at without the filters available on a graph-service rendered one.
