### ISSUE TITLE
milestone burndown date picker

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#2350]
**Acceptance Criteria**
- [x] select a start and end date for the burndown graph
- [x] when selecting a milestone, default it to the milestone start date and end date (if there is one), if possible without upgrading ui-bootstrap
- [x] saves selection in local storage
- [x] figure out a default: last two weeks, ending today?
