### ISSUE TITLE
Auto-work tracking assignees improvements

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#2608]
Add user as an assignee when:
- [ ] When creating a branch referencing an issue, 
- [ ] When pushing a commit to a connected pr
- [ ] Opening a new connected pr

**Comment by homeyer** [comment]
We’re doing some spring cleaning over at Waffle! 🌻

That means we’re closing out some issues we’re not committed to doing in the next 6 months or so, but please feel free to keep commenting on it, we’re still listening! More on our blog: https://blog.waffle.io/managing-large-backlogs-48db59425208
