### ISSUE TITLE
assign milestone from any repo on board to an issue

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3026]
Currently, you can only assign an issue to a milestone that exists for that repo.

AC:
- [x] show the combined list of milestones from all repos
- [x] create the milestone in the repo if necessary, and set the issue to it

Add New Dropdown:
- [x] create new issue without a milestone
- [x] add existing milestone
       - [x] displays properly in on board
       - [x] displays properly in card detail modal
       - [x] correct in GitHub
 - [x] create and add milestone from different repo
       - [x] displays properly in on board
       - [x] displays properly in card detail modal
       - [x] correct in GitHub
Detail Modal:
- [x] add existing milestone
       - [x] displays properly in on board
       - [x] displays properly in card detail modal
       - [x] correct in GitHub
 - [x] create and add milestone from different repo
       - [x] displays properly in on board
       - [x] displays properly in card detail modal
       - [x] correct in GitHub
- [ ] can clear/remove milestone
Burndown Graph:
- [ ] still works

**Comment by harkenn** [comment]
This would be awesome! Huge headache to go around between (literally) a dozen repos and create milestones everywhere.

**Comment by marydavis** [comment]
this is when adding a new issue or adding a milestone via the detail modal right?

**Comment by Alisuehobbs** [comment]
yes
