### ISSUE TITLE
link to burndown graph from card detail view if a milestone is assigned

### ISSUE THREAD

**Issue by homeyer** [waffleio/waffle.io#3028]
AC: 
- [ ] add a metrics icon next to the milestone that links to graph, if a milestone is selected on the detail view
- [ ] add a tooltip "View Burndown Graph"
- [ ] open in new tab?

**Comment by marydavis** [comment]
<img width="186" alt="icon button" src="https://cloud.githubusercontent.com/assets/176437/24064518/4f7c3d36-0b3b-11e7-8ca1-999134d4256a.png">
