### ISSUE TITLE
If a milestone has been renamed recently, sometimes issues still have the previous milestone on them

### ISSUE THREAD

**Issue by kellihsf** [waffleio/waffle.io#3051]
AC:
- [ ] handle webhooks for milestone and label changes
- [ ] find all cards for issues with the affected milestone/label and update them (bulk)
- [ ] make sure to configure pusher to be a silent update (so no banners show for all the cards affected)

**Comment by mginnard** [comment]
+1, just hit this bug pretty hard after renaming milestones across repos.

It not only shows the old milestone on the issue, but it breaks the ability to filter the waffle board by milestone: the filtering menu shows the **new** milestone, while the issues have the **old** milestone.  @kellihsf

**Comment by mginnard** [comment]
### Steps To Reproduce
+ Create multiple issues across multiple repos, assigned to various test milestones (ex: "Test Milestone A", "Test Milestone B").
+ View issues on the waffle board.
+ **Verify:** The milestone names accurately reflect what's on Github.
+ Change the milestone names across repos to a common name (ex: "Test Milestone C").
+ View issues on the waffle board.
+ **Expected Behavior:** Issues would show their updated milestone name, and I could filter by the updated milestone name.
+ **Actual Behavior:** The _majority_ of issues show their old milestone, and the filtering menu shows the new milestone name (and none of the old milestone names).

### Result
You're unable to filter by a milestone after you've updated the milestone name.

**Comment by askel4dd** [comment]
Temp solution: select each card with outdated milestone to force-update them.
