### ISSUE TITLE
Milestone in Modal

### ISSUE THREAD

**Issue by burtonjc** [waffleio/waffle.io#3802]
AC:
- [ ] show/edit milestone in modal
- [ ] can filter milestones in picker
- [ ] can create milestones in picker
- [ ] picker manages milestones across repos

child of https://github.com/waffleio/waffle.io/issues/3779
requires https://github.com/waffleio/waffle.io/issues/3796
requires https://github.com/waffleio/waffle.io/issues/3781
